version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - A:\Cursos\'Programacion reactiva'\Springboot-Webflux\mongodb:/data/db
